-- xiaoquexing-server schema baseline (S1)
-- IDs are uuid generated by the API (UUIDv7). Timestamps are timestamptz UTC.

create table if not exists users (
  id uuid primary key,
  display_name varchar(80) not null default '',
  avatar_object_key text null,
  status varchar(20) not null default 'ACTIVE',
  delete_requested_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint users_status_chk check (status in ('ACTIVE','PENDING_DELETE','DELETED'))
);

create table if not exists auth_identities (
  id uuid primary key,
  user_id uuid not null references users(id) on delete cascade,
  type varchar(20) not null,
  identifier_hash char(64) not null,
  phone_encrypted bytea not null,
  verified_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint auth_identities_type_chk check (type in ('PHONE')),
  constraint auth_identities_hash_uq unique (identifier_hash)
);
create index if not exists auth_identities_user_id_idx on auth_identities (user_id);

create table if not exists devices (
  id uuid primary key,
  user_id uuid not null references users(id) on delete cascade,
  client_device_id varchar(128) not null,
  platform varchar(20) not null default 'unknown',
  app_version varchar(40) not null default '',
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint devices_user_client_uq unique (user_id, client_device_id)
);
create index if not exists devices_user_id_idx on devices (user_id);

create table if not exists refresh_tokens (
  id uuid primary key,
  user_id uuid not null references users(id) on delete cascade,
  device_id uuid not null references devices(id) on delete cascade,
  family_id uuid not null,
  token_hash char(64) not null,
  expires_at timestamptz not null,
  revoked_at timestamptz null,
  replaced_by uuid null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint refresh_tokens_hash_uq unique (token_hash)
);
create index if not exists refresh_tokens_family_idx on refresh_tokens (family_id);
create index if not exists refresh_tokens_user_device_idx on refresh_tokens (user_id, device_id);

create table if not exists spaces (
  id uuid primary key,
  name varchar(100) not null,
  space_type varchar(20) not null,
  owner_id uuid not null references users(id),
  total_gp bigint not null default 0,
  active_plant_type varchar(30) not null default 'TREE',
  timezone varchar(64) not null default 'Asia/Shanghai',
  version bigint not null default 1,
  deleted_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint spaces_type_chk check (space_type in ('PERSONAL','COUPLE','FAMILY','FRIEND'))
);
create index if not exists spaces_owner_idx on spaces (owner_id);

create table if not exists space_members (
  space_id uuid not null references spaces(id) on delete cascade,
  user_id uuid not null references users(id),
  role varchar(20) not null,
  status varchar(20) not null default 'ACTIVE',
  joined_at timestamptz not null default now(),
  left_at timestamptz null,
  contributed_gp bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (space_id, user_id),
  constraint space_members_role_chk check (role in ('OWNER','ADMIN','MEMBER')),
  constraint space_members_status_chk check (status in ('ACTIVE','LEFT','REMOVED'))
);
create index if not exists space_members_user_idx on space_members (user_id);

create table if not exists space_invites (
  id uuid primary key,
  space_id uuid not null references spaces(id) on delete cascade,
  inviter_id uuid not null references users(id),
  token_hash char(64) not null,
  expires_at timestamptz not null,
  max_uses int not null default 1,
  used_count int not null default 0,
  revoked_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint space_invites_token_uq unique (token_hash)
);

create table if not exists records (
  id uuid primary key,
  client_local_id bigint null,
  space_id uuid not null references spaces(id),
  author_id uuid not null references users(id),
  content_text varchar(500) null,
  mood_tag varchar(30) not null,
  occurred_at timestamptz not null,
  occurred_date date not null,
  occurred_timezone varchar(64) not null,
  is_backdated boolean not null default false,
  gp_final int not null default 0,
  gp_capped boolean not null default false,
  gp_breakdown jsonb not null default '{}'::jsonb,
  version bigint not null default 1,
  deleted_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists records_space_occurred_idx on records (space_id, occurred_at desc);
create index if not exists records_author_updated_idx on records (author_id, updated_at desc);
create index if not exists records_space_date_live_idx on records (space_id, occurred_date) where deleted_at is null;

create table if not exists record_media (
  id uuid primary key,
  record_id uuid not null references records(id) on delete cascade,
  type varchar(20) not null,
  sort_order int not null default 0,
  object_key text null,
  upload_status varchar(20) not null default 'PENDING',
  mime_type varchar(100) null,
  size_bytes bigint null,
  sha256 char(64) null,
  width int null,
  height int null,
  duration_ms int null,
  title text null,
  subtitle text null,
  source_url text null,
  extra jsonb not null default '{}'::jsonb,
  version bigint not null default 1,
  deleted_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint record_media_type_chk check (type in ('PHOTO','VOICE','MUSIC','LINK','LOCATION')),
  constraint record_media_status_chk check (upload_status in ('PENDING','READY','MISSING','DELETED'))
);
create index if not exists record_media_record_idx on record_media (record_id, sort_order);

create table if not exists tags (
  id uuid primary key,
  scope varchar(20) not null,
  owner_user_id uuid null references users(id),
  space_id uuid null references spaces(id),
  kind varchar(20) not null,
  name varchar(40) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tags_scope_chk check (scope in ('SYSTEM','USER','SPACE')),
  constraint tags_kind_chk check (kind in ('STATUS','CUSTOM'))
);
create unique index if not exists tags_system_name_uq on tags (kind, name) where scope = 'SYSTEM';
create unique index if not exists tags_user_name_uq on tags (owner_user_id, kind, name) where scope = 'USER';
create unique index if not exists tags_space_name_uq on tags (space_id, kind, name) where scope = 'SPACE';

create table if not exists record_tags (
  record_id uuid not null references records(id) on delete cascade,
  tag_id uuid not null references tags(id),
  primary key (record_id, tag_id)
);

create table if not exists daily_space_stats (
  space_id uuid not null references spaces(id) on delete cascade,
  occurred_date date not null,
  gp_total int not null default 0,
  record_count int not null default 0,
  distinct_author_count int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (space_id, occurred_date),
  constraint daily_space_stats_gp_chk check (gp_total >= 0 and gp_total <= 100)
);

create table if not exists plant_definitions (
  code varchar(30) primary key,
  display_name varchar(80) not null,
  condition_type varchar(40) not null,
  condition_value int not null default 0,
  condition_sub_param varchar(40) null,
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists plant_snapshots (
  id uuid primary key,
  space_id uuid not null references spaces(id) on delete cascade,
  plant_type varchar(30) not null,
  event_type varchar(30) not null,
  stage varchar(30) not null,
  gp_at_event bigint not null default 0,
  occurred_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists plant_snapshots_space_idx on plant_snapshots (space_id, occurred_at);

create table if not exists achievement_definitions (
  code varchar(40) primary key,
  title varchar(80) not null,
  description text not null default '',
  scope varchar(20) not null default 'USER',
  condition_type varchar(40) not null,
  condition_value int not null default 0,
  reward jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists achievement_progress (
  definition_code varchar(40) not null references achievement_definitions(code),
  scope_key varchar(80) not null,
  progress int not null default 0,
  is_unlocked boolean not null default false,
  unlocked_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (definition_code, scope_key)
);

create table if not exists achievement_events (
  id uuid primary key,
  definition_code varchar(40) not null references achievement_definitions(code),
  scope_key varchar(80) not null,
  event_type varchar(20) not null,
  progress_before int not null,
  progress_after int not null,
  reason jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists achievement_events_scope_idx on achievement_events (scope_key, occurred_at desc);

create table if not exists applied_mutations (
  mutation_id uuid primary key,
  user_id uuid not null references users(id),
  device_id uuid null references devices(id),
  request_hash char(64) not null,
  response_json jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists applied_mutations_user_idx on applied_mutations (user_id, created_at desc);

create table if not exists change_log (
  sequence bigserial primary key,
  entity_type varchar(30) not null,
  entity_id uuid not null,
  space_id uuid null,
  version bigint not null default 1,
  op varchar(20) not null,
  payload jsonb not null default '{}'::jsonb,
  changed_at timestamptz not null default now()
);
create index if not exists change_log_space_seq_idx on change_log (space_id, sequence);

create table if not exists albums (
  id uuid primary key,
  space_id uuid not null references spaces(id),
  owner_id uuid not null references users(id),
  title varchar(120) not null,
  theme varchar(40) not null default 'default',
  range_from date null,
  range_to date null,
  layout_seed varchar(64) not null default '',
  entry_hash char(64) null,
  version bigint not null default 1,
  deleted_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists album_pages (
  id uuid primary key,
  album_id uuid not null references albums(id) on delete cascade,
  sort_order int not null,
  page_type varchar(40) not null,
  model jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists album_pages_album_idx on album_pages (album_id, sort_order);

create table if not exists album_shares (
  id uuid primary key,
  album_id uuid not null references albums(id) on delete cascade,
  token_hash char(64) not null,
  expires_at timestamptz not null,
  revoked_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint album_shares_token_uq unique (token_hash)
);

insert into plant_definitions (code, display_name, condition_type, condition_value, condition_sub_param) values
  ('TREE', '小确幸之树', 'DEFAULT', 0, null),
  ('SUNFLOWER', '向日葵', 'DEFAULT', 0, null),
  ('SAKURA', '樱花树', 'STREAK_DAYS', 30, null),
  ('CACTUS', '仙人掌', 'DISTINCT_LOCATION_COUNT', 50, null),
  ('SUCCULENT', '多肉', 'RECORD_COUNT', 100, null),
  ('VINE', '藤蔓', 'SHARED_SPACE_EVENT', 1, 'INVITE_CO_PLANT'),
  ('ROSE', '玫瑰花丛', 'SHARED_SPACE_EVENT', 1, 'COUPLE_SPACE_JOINED'),
  ('BAMBOO', '竹林', 'RECORD_DAY_COUNT', 365, null),
  ('MUSHROOM', '蘑菇', 'HIDDEN_ACHIEVEMENT_COUNT', 3, null)
on conflict (code) do nothing;

insert into achievement_definitions (code, title, description, scope, condition_type, condition_value) values
  ('first_record', '初次记录', '记录你的第一个小确幸', 'USER', 'RECORD_COUNT', 1),
  ('record_10', '记录达人', '累计记录10条小确幸', 'USER', 'RECORD_COUNT', 10),
  ('record_50', '生活记录者', '累计记录50条小确幸', 'USER', 'RECORD_COUNT', 50),
  ('record_100', '坚持者', '累计记录100条小确幸', 'USER', 'RECORD_COUNT', 100),
  ('record_500', '幸福收藏家', '累计记录500条小确幸', 'USER', 'RECORD_COUNT', 500),
  ('streak_7', '一周坚持', '连续记录7天', 'USER', 'STREAK_DAYS', 7),
  ('streak_30', '月度习惯', '连续记录30天', 'USER', 'STREAK_DAYS', 30),
  ('streak_100', '百日达人', '连续记录100天', 'USER', 'STREAK_DAYS', 100),
  ('streak_365', '年度成就', '连续记录365天', 'USER', 'STREAK_DAYS', 365),
  ('photographer', '摄影师', '添加100张照片', 'USER', 'PHOTO_COUNT', 100),
  ('singer', '歌唱家', '分享50首不同歌曲', 'USER', 'MUSIC_SONG_COUNT', 50),
  ('traveler', '旅行者', '记录50个地点', 'USER', 'DISTINCT_LOCATION_COUNT', 50),
  ('share_10', '分享达人', '分享10次记录', 'USER', 'SHARE_COUNT', 10),
  ('influencer', '传播幸福', '分享带来5个新用户', 'USER', 'SHARE_INVITE_USER_COUNT', 5),
  ('botanist', '植物学家', '解锁所有植物', 'USER', 'UNLOCKED_PLANT_COUNT', 9),
  ('music_collector', '旋律收藏家', '收藏50首不同歌曲', 'USER', 'MUSIC_SONG_COUNT', 50),
  ('sharer', '分享者', '完成首次分享', 'USER', 'SHARE_COUNT', 1)
on conflict (code) do nothing;
